name: Moon Frontend Pull Request

on:
  push:
    branches-ignore:
      - main

jobs:
  pr_and_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if PR exists and create if needed
        run: |
          if ! gh pr view ${{ github.ref_name }} &>/dev/null; then
            gh pr create --base main --head ${{ github.ref_name }} --title "${{ github.ref_name }}" --body "Automated PR created from branch ${{ github.ref_name }}"
            echo "Created new PR for branch ${{ github.ref_name }}"
          else
            echo "PR already exists for branch ${{ github.ref_name }}, skipping creation"
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate version
        id: version
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')
          echo "Extracted BRANCH_NAME: ${BRANCH_NAME}"
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
          
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "Extracted SHORT_SHA: ${SHORT_SHA}"
          echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_ENV

      - name: Build and push multi-platform Docker image
        run: |
          echo "Building and pushing Docker image with version: ${BRANCH_NAME}-${SHORT_SHA}"
          make build-push-multi VERSION=${{ env.BRANCH_NAME }}-${{ env.SHORT_SHA }}