name: Moon Frontend Pull Request

on:
  push:
    branches-ignore:
      - main

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check if PR exists and create if needed
        run: |
          if ! gh pr view ${{ github.ref_name }} &>/dev/null; then
            gh pr create --base main --head ${{ github.ref_name }} --title "${{ github.ref_name }}" --body "Automated PR created from branch ${{ github.ref_name }}"
            echo "Created new PR for branch ${{ github.ref_name }}"
          else
            echo "PR already exists for branch ${{ github.ref_name }}, skipping creation"
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
